#!/usr/bin/env python3
"""Toucan offline tests. No serial devices are opened."""
import copy
import contextlib
import hashlib
import importlib.util
import io
import json
from pathlib import Path
import stat
import tempfile
from types import SimpleNamespace
import unittest
from unittest.mock import patch

ROOT = Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location('toucan_backend', ROOT/'keyboards/toucan/backend.py')
b = importlib.util.module_from_spec(spec)
spec.loader.exec_module(b)
DESIRED = b.load(b.HERE/'keymap.json')
READ_TEXT = Path.read_text


def same_user_status(path, *args, **kwargs):
    if str(path) == '/proc/123456/status':
        return f'Uid:\t9999\t{b.os.geteuid()}\t9999\t9999\n'
    return READ_TEXT(path, *args, **kwargs)


class MockRPC:
    def __init__(self):
        self.state = b.original()
        self.pending = False
        self.calls = []
        self.fail = None
        self.mismatch = False
        self.saved = False
        self.before_set = lambda: None

    def call(self, subsystem, method, value=True):
        self.calls.append((subsystem,method,copy.deepcopy(value)))
        if method == self.fail:
            raise OSError('mock disconnect/failure')
        if method == 'get_device_info':
            return copy.deepcopy(self.state['device_info'])
        if method == 'get_lock_state':
            return 1
        if method == 'check_unsaved_changes':
            return self.pending
        if method == 'get_keymap':
            result = copy.deepcopy(self.state['keymap'])
            if self.saved and self.mismatch:
                result['layers'][0]['name'] = 'mismatch'
            return result
        if method == 'get_physical_layouts':
            return copy.deepcopy(self.state['physical_layouts'])
        if method == 'list_all_behaviors':
            return copy.deepcopy(self.state['available_behaviors'])
        if method == 'get_behavior_details':
            return copy.deepcopy(self.state['behavior_details'][str(value['behavior_id'])])
        if method in ('set_layer_binding','set_layer_props'):
            self.before_set()
            layer = next(l for l in self.state['keymap']['layers'] if l['id'] == value['layer_id'])
            if method == 'set_layer_props':
                layer['name'] = value['name']
            else:
                layer['bindings'][value['key_position']] = copy.deepcopy(value['binding'])
            self.pending = True
            return 0
        if method == 'save_changes':
            self.pending = False
            self.saved = True
            return {'ok':True}
        raise AssertionError(method)

    def mutations(self):
        return [m for _,m,_ in self.calls if m in b.SETTERS]


class ToucanTest(unittest.TestCase):
    def test_original_hashes(self):
        retained = 0
        for line in (b.ORIGINALS/'SHA256SUMS').read_text().splitlines():
            digest, name = line.split(maxsplit=1)
            path = b.ORIGINALS/Path(name.lstrip('*')).name
            if path.exists():
                self.assertEqual(hashlib.sha256(path.read_bytes()).hexdigest(), digest, name)
                retained += 1
        self.assertEqual(retained, 9)

    def test_golden_wire_payloads(self):
        enum = {'ZMK_STUDIO_CORE_LOCK_STATE_UNLOCKED':1, 'GENERIC':0}
        def normalize(value):
            if isinstance(value,dict):
                return {k:normalize(v) for k,v in value.items()}
            if isinstance(value,list):
                return [normalize(v) for v in value]
            return enum.get(value,value) if isinstance(value,str) else value
        count = 0
        for line in (b.ORIGINALS/'rpc.jsonl').read_text().splitlines():
            record = json.loads(line)
            if 'protobuf_hex' not in record:
                continue
            decoded = b.protocol.decode('Response', bytes.fromhex(record['protobuf_hex']))
            self.assertEqual(decoded, normalize(record['response']))
            self.assertEqual(b.protocol.decode('Response', b.protocol.encode('Response', decoded)), decoded)
            count += 1
        self.assertEqual(count,34)

    def test_wire_setters_stable_id_and_signed_behavior(self):
        value = {'request_id':1, 'keymap':{'set_layer_binding':{'layer_id':2,
                 'key_position':13,'binding':{'behavior_id':14,'param1':458979,'param2':458756}}}}
        self.assertEqual(b.protocol.decode('Request', b.protocol.encode('Request',value)),value)
        # Golden generated by the inspected pinned upstream protobuf implementation.
        self.assertEqual(b.protocol.encode('Request',value).hex(),
                         '08012a1212100802100d1a0a081c10e3811c1884801c')
        self.assertEqual(b.protocol.encode('Request',{'request_id':1,'keymap':{'save_changes':True}}).hex(),
                         '08012a022001')
        self.assertEqual(b.protocol.encode('Request',{'request_id':1,'keymap':{'set_layer_props':{
                         'layer_id':3,'name':'Functions'}}}).hex(),
                         '08012a0f620d0803120946756e6374696f6e73')
        # Behavior ID is sint32, NOT uint32: 14 is encoded as 28.
        self.assertEqual(b.protocol.encode('Binding',{'behavior_id':14}),b'\x08\x1c')
        self.assertEqual(b.protocol.decode('BehaviorList', b'\x0a\x03\x01\x02\x03'),{'behaviors':[1,2,3]})

    def test_bad_wire(self):
        for data in (b'\x08\x80',b'\x0a\x05a',b'\x00',b'\xff'*12):
            with self.assertRaises(ValueError):
                b.protocol.decode('Response',data)

    def test_transport_frames_errors_and_timeout(self):
        def framed(response):
            raw = b.protocol.encode('Response',response)
            return b'\xab'+b''.join((b'\xac' if v in (171,172,173) else b'')+bytes([v])
                                    for v in raw)+b'\xad'
        def run(data, *, timeout=False):
            rpc = b.SerialRPC()
            rpc.fd = 999  # mocked; no device open
            data = iter(bytes([v]) for v in data)
            def ready(read,write,_,seconds):
                return ([] if timeout else read, write, [])
            with patch.object(b.os,'write',side_effect=lambda fd,buf:min(2,len(buf))), \
                 patch.object(b.os,'read',side_effect=lambda *_:next(data,b'')), \
                 patch.object(b.select,'select',side_effect=ready):
                return rpc.call('core','get_device_info')
        info = {'name':'Toucan','serial_number':'q6yt'}  # bytes AB AC AD need escaping
        response = {'request_response':{'request_id':1,'core':{'get_device_info':info}}}
        notification = {'notification':{'keymap':{'unsaved_changes_status_changed':False}}}
        self.assertEqual(run(framed(notification)+framed(response)),info)
        with self.assertRaisesRegex(b.Error,'request ID'):
            run(framed({'request_response':{'request_id':2,'core':{'get_device_info':info}}}))
        with self.assertRaisesRegex(b.Error,'RPC error'):
            run(framed({'request_response':{'request_id':1,'meta':{'simple_error':1}}}))
        with self.assertRaisesRegex(b.Error,'locked'):
            run(framed({'notification':{'core':{'lock_state_changed':0}}}))
        with self.assertRaisesRegex(b.Error,'disconnected'):
            run(b'\xab\x0a')
        with self.assertRaises(TimeoutError):
            run(b'',timeout=True)

    def test_inaccessible_process_warns_once_per_session(self):
        properties = '\n'.join(k+'='+v for k,v in b.original()['usb_identity'].items())
        def entries(path):
            if str(path) == '/proc':
                return iter([Path('/proc/123456'), Path('/proc/234567')])
            if path.name == 'fd':
                if inaccessible == 'fd':
                    raise PermissionError('not visible')
                return iter([path/'7', path/'8'])
            raise AssertionError(path)
        def read_text(path, *args, **kwargs):
            if str(path).startswith('/proc/'):
                if inaccessible == 'status':
                    raise PermissionError('unrelated process status not visible')
                return f'Uid:\t9999\t{b.os.geteuid()}\t9999\t9999\n'
            return READ_TEXT(path, *args, **kwargs)
        with patch.object(b.subprocess,'run',return_value=SimpleNamespace(stdout=properties)), \
             patch.object(b.os,'open',return_value=999), patch.object(b.os,'close') as close, \
             patch.object(b.os,'write') as write, patch.object(b.fcntl,'flock'), \
             patch.object(b.fcntl,'ioctl'), \
             patch.object(b.os,'fstat',return_value=SimpleNamespace(st_mode=stat.S_IFCHR,st_rdev=1)), \
             patch.object(Path,'read_text',read_text), patch.object(Path,'iterdir',entries), \
             patch.object(Path,'stat',side_effect=PermissionError('hidden FD link')), \
             patch.object(b.termios,'tcgetattr',return_value=[0,0,0,0,0,0,[0]*32]), \
             patch.object(b.termios,'tcsetattr'):
            for inaccessible in ('status', 'fd', 'link'):
                with self.subTest(inaccessible=inaccessible), \
                     contextlib.redirect_stderr(io.StringIO()) as errors, \
                     contextlib.redirect_stdout(io.StringIO()) as output:
                    with b.SerialRPC() as rpc:
                        self.assertEqual(rpc.fd,999)
                    self.assertEqual(errors.getvalue().count('warning:'),1)
                    self.assertIn('same-effective-UID access audit incomplete',errors.getvalue())
                    self.assertIn('not system-wide exclusivity',errors.getvalue())
                    self.assertEqual(output.getvalue(),'')
            write.assert_not_called()
            self.assertEqual(close.call_count,3)

    def test_competing_handle_refuses_before_rpc(self):
        properties = '\n'.join(k+'='+v for k,v in b.original()['usb_identity'].items())
        def entries(path):
            if str(path) == '/proc':
                return iter([Path('/proc/234567'), Path('/proc/123456')])
            return iter([path/'6', path/'7'])
        def read_text(path, *args, **kwargs):
            if str(path) == '/proc/234567/status':
                raise PermissionError('unrelated process status not visible')
            return same_user_status(path, *args, **kwargs)
        def fd_stat(path):
            if path.name == '6':
                raise PermissionError('hidden FD link')
            return device
        device = SimpleNamespace(st_mode=stat.S_IFCHR,st_rdev=1)
        with patch.object(b.subprocess,'run',return_value=SimpleNamespace(stdout=properties)), \
             patch.object(b.os,'open',return_value=999), patch.object(b.os,'close') as close, \
             patch.object(b.os,'write') as write, patch.object(b.fcntl,'flock'), \
             patch.object(b.fcntl,'ioctl'), patch.object(b.os,'fstat',return_value=device), \
             patch.object(Path,'stat',fd_stat), patch.object(Path,'iterdir',entries), \
             patch.object(Path,'read_text',read_text):
            with self.assertRaisesRegex(b.Error,'already open'):
                with b.SerialRPC():
                    self.fail('must not obtain a usable transport')
            write.assert_not_called()
            close.assert_called_once_with(999)

    def test_other_effective_uid_skips_fd_audit(self):
        properties = '\n'.join(k+'='+v for k,v in b.original()['usb_identity'].items())
        def entries(path):
            self.assertEqual(str(path),'/proc')  # Accessing the other user's FDs is forbidden.
            return iter([Path('/proc/123456')])
        def read_text(path, *args, **kwargs):
            if str(path) == '/proc/123456/status':
                return f'Uid:\t{b.os.geteuid()}\t{b.os.geteuid()+1}\t0\t0\n'
            return READ_TEXT(path,*args,**kwargs)
        with patch.object(b.subprocess,'run',return_value=SimpleNamespace(stdout=properties)), \
             patch.object(b.os,'open',return_value=999), patch.object(b.os,'close'), \
             patch.object(b.os,'write') as write, patch.object(b.fcntl,'flock') as flock, \
             patch.object(b.fcntl,'ioctl') as ioctl, \
             patch.object(b.os,'fstat',return_value=SimpleNamespace(st_mode=stat.S_IFCHR,st_rdev=1)), \
             patch.object(Path,'iterdir',entries), patch.object(Path,'read_text',read_text), \
             patch.object(b.termios,'tcgetattr',return_value=[0,0,0,0,0,0,[0]*32]), \
             patch.object(b.termios,'tcsetattr'):
            with b.SerialRPC():
                pass
            flock.assert_called_once_with(999,b.fcntl.LOCK_EX | b.fcntl.LOCK_NB)
            self.assertEqual(ioctl.call_args_list[0].args,(999,b.termios.TIOCEXCL))
            write.assert_not_called()

    def test_sysfs_status_absent_and_present(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            usb = root/'bus/usb/devices'
            tty = root/'class/tty'
            usb.mkdir(parents=True)
            tty.mkdir(parents=True)
            with patch.object(b,'SerialRPC') as serial, patch.object(b.subprocess,'run') as run:
                self.assertFalse(b.status(sysfs_root=root)['present'])
                device = usb/'1-1'
                device.mkdir()
                for key,value in {'idVendor':'1d50','idProduct':'615e','serial':'93F54E4E61BA5937'}.items():
                    (device/key).write_text(value+'\n')
                interface = device/'1-1:1.0'
                interface.mkdir()
                (tty/'ttyACM0').mkdir()
                (tty/'ttyACM0/device').symlink_to(interface)
                result = b.status(sysfs_root=root)
                self.assertTrue(result['present'])
                self.assertEqual(result['devices'][0]['ports'],['/dev/ttyACM0'])
                self.assertEqual(result['studio_state'],'not queried')
                (device/'serial').write_text('wrong-device')
                self.assertFalse(b.status(sysfs_root=root)['present'])
                serial.assert_not_called()
                run.assert_not_called()

    def test_main_status_does_not_load_keymap_or_open_device(self):
        result = {'present':False,'devices':[],'source':'sysfs','studio_state':'not queried'}
        with patch.object(b,'status',return_value=result), patch.object(b,'load') as load, \
             patch.object(b,'SerialRPC') as serial, contextlib.redirect_stdout(io.StringIO()) as output:
            self.assertEqual(b.main(['status','--keymap','/missing/keymap.json']),0)
            self.assertEqual(json.loads(output.getvalue()),result)
            serial.assert_not_called()
            load.assert_not_called()

    def test_main_apply_requires_layout_review_before_connection(self):
        with patch.object(b,'SerialRPC') as serial, patch.object(b,'load') as load, \
             contextlib.redirect_stderr(io.StringIO()) as errors:
            self.assertEqual(b.main(['apply']),1)
            self.assertIn('--ack-layout-review',errors.getvalue())
            serial.assert_not_called()
            load.assert_not_called()
        with patch.object(b,'SerialRPC') as serial, patch.object(b,'apply',return_value={'changed':False}) as apply, \
             contextlib.redirect_stdout(io.StringIO()):
            self.assertEqual(b.main(['apply','--ack-layout-review']),0)
            serial.assert_called_once_with(b.PORT,writable=True)
            apply.assert_called_once()

    def test_mapping(self):
        b.validate(DESIRED)
        layers = {l['id']:l['bindings'] for l in DESIRED['layers']}
        old = {l['id']:l['bindings'] for l in b.original()['keymap']['layers']}
        self.assertEqual(layers[0][24:42],old[0][24:42])
        for p in (13,14,15,16,19,20,21,22):
            self.assertEqual(layers[0][p]['behavior_id'],14)
            self.assertEqual(layers[0][p]['param2'],old[0][p]['param1'])
        for p in (17,25,28,29):
            self.assertEqual(layers[1][p],old[1][p])
        self.assertEqual([layers[1][p]['param1'] for p in (32,33)],[0xc00ea,0xc00e9])
        for p in (0,41):
            self.assertEqual(layers[3][p],{'behavior_id':4,'param1':0,'param2':0})
        self.assertEqual(layers[3][13:23],old[3][13:23])
        self.assertEqual([layers[3][p]['param2'] for p in (1,2,3)],[0,1,2])
        self.assertEqual([layers[3][p]['param1'] for p in (4,5)],[0x70044,0x70045])

    def previous_personal_map(self):
        previous = copy.deepcopy(DESIRED)
        for pos, binding in {
                30: {'behavior_id':23,'param1':0,'param2':0},
                32: {'behavior_id':22,'param1':2,'param2':0},
                33: {'behavior_id':22,'param1':1,'param2':0},
                34: {'behavior_id':8,'param1':458981,'param2':0}}.items():
            previous['layers'][-1]['bindings'][pos] = binding
        for pos in (0,41):
            previous['layers'][-1]['bindings'][pos] = b.original()['keymap']['layers'][-1]['bindings'][pos]
        # Pin the entire previous personal map, independently of Git/worktree state.
        encoded = json.dumps(previous,sort_keys=True,separators=(',',':')).encode()
        self.assertEqual(hashlib.sha256(encoded).hexdigest(),
                         '47a756d7a97525b5b64d889a4083abd11d6cf2bf86af2759f7dc0d49b1ced38e')
        return previous

    def test_none_correction_two_only_delta_and_apply(self):
        rpc = MockRPC()
        rpc.state['keymap'] = self.previous_personal_map()
        corrected = copy.deepcopy(rpc.state['keymap'])
        for pos in (0,41):
            corrected['layers'][-1]['bindings'][pos] = {'behavior_id':4,'param1':0,'param2':0}
        changes = b.diff(rpc.state,corrected)
        self.assertEqual(changes,[
            {'method':'set_layer_binding',
             'request':{'layer_id':3,'key_position':pos,
                        'binding':{'behavior_id':4,'param1':0,'param2':0}},
             'before':rpc.state['keymap']['layers'][-1]['bindings'][pos]}
            for pos in (0,41)])
        with tempfile.TemporaryDirectory() as root:
            result = b.apply(rpc,corrected,backup_root=root)
        self.assertEqual(result['changes'],changes)
        self.assertEqual(rpc.mutations(),['set_layer_binding','set_layer_binding','save_changes'])
        self.assertEqual(rpc.state['keymap'],corrected)
        self.assertTrue(b.verify(rpc,corrected)['verified'])

    def test_bluetooth_four_only_delta_and_apply(self):
        rpc = MockRPC()
        rpc.state['keymap'] = self.previous_personal_map()
        for pos in (0,41):
            rpc.state['keymap']['layers'][-1]['bindings'][pos] = {'behavior_id':4,'param1':0,'param2':0}
        changes = b.diff(rpc.state,DESIRED)
        self.assertEqual(changes,[
            {'method':'set_layer_binding',
             'request':{'layer_id':3,'key_position':pos,
                        'binding':{'behavior_id':bid,'param1':p1,'param2':0}},
             'before':rpc.state['keymap']['layers'][-1]['bindings'][pos]}
            for pos,bid,p1 in ((30,22,0),(32,4,0),(33,22,2),(34,22,1))])
        with tempfile.TemporaryDirectory() as root:
            result = b.apply(rpc,DESIRED,backup_root=root)
        self.assertEqual(result['changes'],changes)
        self.assertEqual(rpc.mutations(),['set_layer_binding']*4+['save_changes'])
        self.assertEqual(rpc.state['keymap'],DESIRED)
        self.assertTrue(b.verify(rpc,DESIRED)['verified'])

    def test_clear_only_at_reviewed_position(self):
        for index in range(4):
            for pos in range(42):
                for p1,p2 in ((0,0),(0,1),(4,0),(5,0)):
                    if (index,pos,p1,p2) == (3,30,0,0):
                        continue
                    want = copy.deepcopy(DESIRED)
                    want['layers'][index]['bindings'][pos] = {'behavior_id':22,'param1':p1,'param2':p2}
                    rpc = MockRPC()
                    with self.subTest(index=index,pos=pos,p1=p1,p2=p2):
                        with self.assertRaises(b.Error):
                            b.apply(rpc,want)
                        rpc.state['keymap'] = copy.deepcopy(want)
                        with self.assertRaises(b.Error):
                            b.diff(rpc.state,want)
                        self.assertEqual(rpc.mutations(),[])

    def test_clear_requires_firmware_metadata(self):
        for kind in ('unadvertised','missing','changed','invalid_parameters'):
            rpc = MockRPC()
            if kind == 'unadvertised': rpc.state['available_behaviors']['behaviors'].remove(22)
            if kind == 'missing': del rpc.state['behavior_details']['22']
            if kind == 'changed': rpc.state['behavior_details']['22']['display_name'] = 'Different'
            if kind == 'invalid_parameters':
                choices = rpc.state['behavior_details']['22']['metadata'][0]['param1']
                choices[:] = [choice for choice in choices if choice['constant'] != 0]
            with self.subTest(kind=kind), self.assertRaises(b.Error):
                # Matching captured metadata still must accept the clear parameters.
                with patch.object(b,'original',return_value=copy.deepcopy(rpc.state)) if kind == 'invalid_parameters' else contextlib.nullcontext():
                    b.diff(rpc.state,DESIRED)
            self.assertEqual(rpc.mutations(),[])

    def test_legacy_snapshot_readonly_verification(self):
        for keymap in (b.original()['keymap'],self.previous_personal_map()):
            rpc = MockRPC()
            rpc.state['keymap'] = keymap
            fresh = b.snapshot(rpc)
            self.assertEqual(b.diff(fresh,fresh['keymap']),[])
            self.assertTrue(b.verify(rpc,fresh['keymap'])['verified'])
            self.assertEqual(rpc.mutations(),[])

    def test_anomaly_restoration_rejected_after_correction(self):
        for pos in (0,41):
            rpc = MockRPC()
            rpc.state['keymap'] = self.previous_personal_map()
            want = copy.deepcopy(rpc.state['keymap'])
            rpc.state['keymap']['layers'][-1]['bindings'][pos] = copy.deepcopy(
                DESIRED['layers'][-1]['bindings'][pos])
            with self.subTest(pos=pos):
                for operation in (lambda: b.diff(rpc.state,want),
                                  lambda: b.verify(rpc,want),
                                  lambda: b.apply(rpc,want)):
                    with self.assertRaisesRegex(b.Error,'restoration unsupported'):
                        operation()
                self.assertEqual(rpc.mutations(),[])

    def test_anomaly_alternatives_rejected_even_when_live_matches(self):
        alternatives = [
            {'behavior_id':23,'param1':0,'param2':0},
            {'behavior_id':8,'param1':458795,'param2':0},
            {'behavior_id':12,'param1':1,'param2':0},
            {'behavior_id':4,'param1':1,'param2':0},
            {'behavior_id':4,'param1':0,'param2':1},
        ]
        for pos in (0,41):
            other_anomaly = b.original()['keymap']['layers'][-1]['bindings'][41-pos]
            for binding in alternatives + [other_anomaly]:
                for matching_live in (False,True):
                    rpc = MockRPC()
                    want = copy.deepcopy(DESIRED)
                    want['layers'][-1]['bindings'][pos] = copy.deepcopy(binding)
                    if matching_live:
                        rpc.state['keymap'] = copy.deepcopy(want)
                    with self.subTest(pos=pos,binding=binding,matching_live=matching_live):
                        with self.assertRaises(b.Error):
                            b.apply(rpc,want)
                        with self.assertRaises(b.Error):
                            b.diff(rpc.state,want)
                        self.assertEqual(rpc.mutations(),[])

    def test_none_correction_requires_firmware_metadata(self):
        for kind in ('unadvertised','missing','changed'):
            rpc = MockRPC()
            if kind == 'unadvertised': rpc.state['available_behaviors']['behaviors'].remove(4)
            if kind == 'missing': del rpc.state['behavior_details']['4']
            if kind == 'changed': rpc.state['behavior_details']['4']['display_name'] = 'Different'
            with self.subTest(kind=kind), self.assertRaisesRegex(b.Error,'identity/schema mismatch: 4'):
                b.diff(rpc.state,DESIRED)
            self.assertEqual(rpc.mutations(),[])

    def test_readonly(self):
        rpc = MockRPC()
        snap = b.snapshot(rpc)
        self.assertTrue(b.diff(snap, DESIRED))
        with self.assertRaises(b.Error):
            b.verify(rpc, DESIRED)
        self.assertEqual(rpc.mutations(),[])
        with self.assertRaises(b.Error):
            b.SerialRPC().call('keymap','save_changes')
        with self.assertRaises(b.Error):
            b.SerialRPC(writable=True).call('core','reset_settings')

    def test_pending_refusal_and_noop(self):
        rpc = MockRPC()
        rpc.pending = True
        with self.assertRaises(b.Error):
            b.apply(rpc,DESIRED)
        self.assertEqual(rpc.mutations(),[])
        rpc.pending = False
        rpc.state['keymap'] = copy.deepcopy(DESIRED)
        self.assertFalse(b.apply(rpc,DESIRED)['changed'])
        self.assertEqual(rpc.mutations(),[])

    def test_complete_validation_before_writes(self):
        for kind in ('late_invalid','bool','missing','layer','unknown','anomaly','bond_clear'):
            rpc = MockRPC()
            want = copy.deepcopy(DESIRED)
            binding = want['layers'][-1]['bindings'][40]
            if kind == 'late_invalid': binding['param1'] = 0xffffffff
            if kind == 'bool': binding['param1'] = True
            if kind == 'missing': del binding['param2']
            if kind == 'layer': want['layers'][0]['bindings'][37]['param1'] = 42
            if kind == 'unknown': binding['behavior_id'] = 999
            if kind == 'anomaly': want['layers'][-1]['bindings'][41]['behavior_id'] = 23
            if kind == 'bond_clear': want['layers'][-1]['bindings'][1]['param1'] = 0
            with self.subTest(kind=kind), self.assertRaises(b.Error):
                b.apply(rpc,want)
            self.assertEqual(rpc.mutations(),[])

    def test_identity_metadata_geometry_drift(self):
        for key in ('device_info','behavior_details','physical_layouts'):
            rpc = MockRPC()
            if key == 'device_info': rpc.state[key]['name'] = 'Other'
            if key == 'behavior_details': rpc.state[key]['14']['display_name'] = 'Different'
            if key == 'physical_layouts': rpc.state[key]['active_layout_index'] = 1
            with self.assertRaises(b.Error): b.apply(rpc,DESIRED)
            self.assertEqual(rpc.mutations(),[])

    def test_locked_refusal(self):
        rpc = MockRPC()
        original_call = rpc.call
        rpc.call = lambda s,m,v=True: 0 if m == 'get_lock_state' else original_call(s,m,v)
        with self.assertRaisesRegex(b.Error,'Studio locked'):
            b.apply(rpc,DESIRED)
        self.assertEqual(rpc.mutations(),[])

    def test_protected_controls(self):
        protected = ([(index,pos) for index in range(4) for pos in range(36,42)
                      if (index,pos) != (3,41)]
                     + [(0,pos) for pos in range(24,36)]
                     + [(2,pos) for pos in (17,25,28,29)])
        for index,position in protected:
            desired = copy.deepcopy(DESIRED)
            desired['layers'][index]['bindings'][position] = {'behavior_id':4,'param1':0,'param2':0}
            with self.subTest(index=index,position=position), self.assertRaisesRegex(b.Error,'protected'):
                b.validate(desired)

    def test_backup_save_readback_reapply(self):
        rpc = MockRPC()
        with tempfile.TemporaryDirectory() as root:
            def check_backup():
                dirs = list(Path(root).iterdir())
                self.assertEqual(len(dirs),1)
                for name in ('before.json','desired.json','diff.json'):
                    path = dirs[0]/name
                    self.assertTrue(path.exists())
                    self.assertEqual(path.stat().st_mode & 0o777,0o600)
            rpc.before_set = check_backup
            result = b.apply(rpc,DESIRED,backup_root=root)
            self.assertTrue(result['changed'])
            self.assertEqual(rpc.state['keymap'],DESIRED)
            self.assertEqual(rpc.mutations().count('save_changes'),1)
            self.assertTrue((Path(result['backup'])/'result.json').exists())
            rpc.calls.clear()
            self.assertFalse(b.apply(rpc,DESIRED,backup_root=root)['changed'])
            self.assertEqual(rpc.mutations(),[])

    def test_backup_rejects_repository_and_symlink_alias_before_mkdir(self):
        with tempfile.TemporaryDirectory() as tmp:
            alias = Path(tmp) / 'repo'
            alias.symlink_to(ROOT, target_is_directory=True)
            for root in (ROOT, ROOT / '.state', ROOT / 'keyboards/snapshots',
                         alias, alias / '.state'):
                for explicit in (True, False):
                    rpc = MockRPC()
                    with self.subTest(root=root, explicit=explicit), \
                            patch.dict(b.os.environ, {'XDG_STATE_HOME': str(root)}), \
                            patch.object(Path, 'mkdir') as mkdir:
                        with self.assertRaisesRegex(b.Error, 'outside the repository'):
                            b.apply(rpc, DESIRED, backup_root=root if explicit else None)
                        mkdir.assert_not_called()
                        self.assertEqual(rpc.mutations(), [])

    def test_failures_leave_recovery_record(self):
        for failure in ('set_layer_binding','save_changes','mismatch'):
            rpc = MockRPC()
            rpc.fail = failure
            rpc.mismatch = failure == 'mismatch'
            with tempfile.TemporaryDirectory() as root:
                with self.subTest(failure=failure), self.assertRaisesRegex(b.Error,'recovery:'):
                    b.apply(rpc,DESIRED,backup_root=root)
                self.assertEqual(len(list(Path(root).glob('*/failure.json'))),1)
                if failure == 'set_layer_binding':
                    self.assertNotIn('save_changes',rpc.mutations())

    def test_backup_failure_prevents_writes(self):
        rpc = MockRPC()
        with tempfile.TemporaryDirectory() as root, patch.object(b,'write_record',side_effect=OSError('disk full')):
            with self.assertRaises(OSError): b.apply(rpc,DESIRED,backup_root=root)
        self.assertEqual(rpc.mutations(),[])

    def test_ram_mismatch_prevents_save(self):
        rpc = MockRPC()
        original_call = rpc.call
        def call(subsystem,method,value=True):
            result = original_call(subsystem,method,value)
            if method == 'get_keymap' and rpc.pending:
                result['layers'][0]['name'] = 'bad RAM'
            return result
        rpc.call = call
        with tempfile.TemporaryDirectory() as root:
            with self.assertRaisesRegex(b.Error,'RAM readback mismatch'):
                b.apply(rpc,DESIRED,backup_root=root)
        self.assertNotIn('save_changes',rpc.mutations())

    def test_error_acknowledgments(self):
        for method, error in (('set_layer_binding',3), ('set_layer_props',1),
                              ('save_changes',{'err':3})):
            rpc = MockRPC()
            original_call = rpc.call
            def call(subsystem,m,value=True):
                result = original_call(subsystem,m,value)
                return error if m == method else result
            rpc.call = call
            with tempfile.TemporaryDirectory() as root:
                with self.subTest(method=method), self.assertRaises(b.Error):
                    b.apply(rpc,DESIRED,backup_root=root)
            if method != 'save_changes':
                self.assertNotIn('save_changes',rpc.mutations())

    def test_late_unsaved_race_prevents_writes(self):
        rpc = MockRPC()
        original_write = b.write_record
        def write(path,value):
            original_write(path,value)
            rpc.pending = True
        with tempfile.TemporaryDirectory() as root, patch.object(b,'write_record',side_effect=write):
            with self.assertRaisesRegex(b.Error,'changed after preflight'):
                b.apply(rpc,DESIRED,backup_root=root)
        self.assertEqual(rpc.mutations(),[])


if __name__ == '__main__':
    unittest.main()
