[dotfiles "github-vps"]
	enabled = true
[credential "https://github.com"]
	helper =
	helper = !~/.local/share/dotfiles/bin/dotfiles-github-auth
	useHttpPath = true
[credential "http://github.com"]
	helper =
	helper = !~/.local/share/dotfiles/bin/dotfiles-github-auth
	useHttpPath = true
