# area ordered-qualified-packages
git upstream/git,generic/git,common/git
bash upstream/bash,upstream/starship,generic/bash,wsl/bash,common/bash
tmux upstream/tmux,generic/tmux,wsl/tmux,common/tmux
nvim upstream/nvim,generic/nvim,common/nvim
zsh common/zsh
