# NuPhy Air60 V2, wired USB and Bluetooth connections.

[ids]
k:19f5:3255:0d7157bb
k:19f5:3246:838051e9

include shared-layers

[num]
semicolon = 6
h = 7
j = 8
k = 9
l = 0

backslash = ^
y = &
u = *
i = (
o = )
p = noop

apostrophe = ~
